name: dd_app
description: Travel Made Simple

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  pinput: any
  flutter_svg: any
  qr_code_scanner: ^0.4.0
  shared_preferences: ^2.0.5
  flutter_native_splash: ^1.1.7+1
  pull_to_refresh: ^1.6.4
  url_launcher: ^6.0.3
  image_picker: ^0.7.4
  dio: ^4.0.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/homepage/

